steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-southwest1-docker.pkg.dev/fh-nest-microservices/image-registtry/products-microservice",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-southwest1-docker.pkg.dev/fh-nest-microservices/image-registtry/products-microservice",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
